### ISSUE TITLE
Error. Need update

### ISSUE THREAD

**Issue by kl-am97** [infinyte7/Chinese-Vocabulary-Generator-Anki-Addon#3]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Chinese Support Redux v0142:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\klari\AppData\Roaming\Anki2\addons21\1128979221\__init__.py", line 23, in <module>
    from . import main
  File "C:\Users\klari\AppData\Roaming\Anki2\addons21\1128979221\main.py", line 32, in <module>
    from .gui import load_menu, unload_menu
  File "C:\Users\klari\AppData\Roaming\Anki2\addons21\1128979221\gui.py", line 22, in <module>
    from PyQt5.QtGui import QKeySequence
ModuleNotFoundError: No module named 'PyQt5'

When loading Chinese Vocabulary Generator:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\klari\AppData\Roaming\Anki2\addons21\1370756741\__init__.py", line 193, in <module>
    dialog = CVG_Dialog()
  File "C:\Users\klari\AppData\Roaming\Anki2\addons21\1370756741\__init__.py", line 41, in __init__
    QDialog.__init__(self, None, Qt.Window)
AttributeError: type object 'Qt' has no attribute 'Window'

**Comment by krmanik** [comment]
Next updates will have fixes.
